<a href="https://colab.research.google.com/github/Joaovtmendes/Dnc-engineer/blob/main/regress_nao_linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [83]:
import pandas as pd
import numpy as np

In [84]:
house = pd.read_excel("house.xlsx")

In [85]:
house.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,ExterQual,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,1,60,65.0,8450,7,5,2003,2003,196.0,Gd,...,0,61,0,0,0,0,0,2,2008,208500
1,2,20,80.0,9600,6,8,1976,1976,0.0,TA,...,298,0,0,0,0,0,0,5,2007,181500
2,3,60,68.0,11250,7,5,2001,2002,162.0,Gd,...,0,42,0,0,0,0,0,9,2008,223500
3,4,70,60.0,9550,7,5,1915,1970,0.0,TA,...,0,35,272,0,0,0,0,2,2006,140000
4,5,60,84.0,14260,8,5,2000,2000,350.0,Gd,...,192,84,0,0,0,0,0,12,2008,250000

In [86]:
house.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [87]:
house = house.dropna()
house.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1121 entries, 0 to 1459
Data columns (total 40 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1121 non-null   int64
 1   MSSubClass     1121 non-null   int64
 2   LotFrontage    1121 non-null   float64
 3   LotArea        1121 non-null   int64
 4   OverallQual    1121 non-null   int64
 5   OverallCond    1121 non-null   int64
 6   YearBuilt      1121 non-null   int64
 7   YearRemodAdd   1121 non-null   int64
 8   MasVnrArea     1121 non-null   float64
 9   ExterQual      1121 non-null   object
 10  ExterCond      1121 non-null   object
 11  BsmtFinSF1     1121 non-null   int64
 12  BsmtFinSF2     1121 non-null   int64
 13  BsmtUnfSF      1121 non-null   int64
 14  TotalBsmtSF    1121 non-null   int64
 15  1stFlrSF       1121 non-null   int64
 16  2ndFlrSF       1121 non-null   int64
 17  LowQualFinSF   1121 non-null   int64
 18  GrLivArea      1121 non-null   int64
 19  BsmtFullBath   1121 non-null   int64
 20  BsmtHalfBath   1121 non-null   int64
 21  FullBath       1121 non-null   int64
 22  HalfBath       1121 non-null   int64
 23  BedroomAbvGr   1121 non-null   int64
 24  KitchenAbvGr   1121 non-null   int64
 25  TotRmsAbvGrd   1121 non-null   int64
 26  Fireplaces     1121 non-null   int64
 27  GarageYrBlt    1121 non-null   float64
 28  GarageCars     1121 non-null   int64
 29  GarageArea     1121 non-null   int64
 30  WoodDeckSF     1121 non-null   int64
 31  OpenPorchSF    1121 non-null   int64
 32  EnclosedPorch  1121 non-null   int64
 33  3SsnPorch      1121 non-null   int64
 34  ScreenPorch    1121 non-null   int64
 35  PoolArea       1121 non-null   int64
 36  MiscVal        1121 non-null   int64
 37  MoSold         1121 non-null   int64
 38  YrSold         1121 non-null   int64
 39  SalePrice      1121 non-null   int64
dtypes: float64(3), int64(35), object(2)
memory usage: 359.1+ KB

In [88]:
house = pd.get_dummies(house).astype(float)

In [89]:
labels = np.array(house['SalePrice'])

features= house.drop('SalePrice', axis = 1)

feature_list = list(features.columns)

features = np.array(features)

In [90]:

from sklearn.model_selection import train_test_split

train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.25, random_state = 42)

In [98]:
from sklearn.datasets import make_moons
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,AdaBoostClassifier,GradientBoostingClassifier
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor, GradientBoostingRegressor
from sklearn import metrics

In [93]:
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)

rf.fit(train_features, train_labels);

In [102]:

predictions_rf = rf.predict(test_features)

errors_rf = abs(predictions_rf - test_labels)

print('Mean Absolute Error:', round(np.mean(errors_rf), 2), 'degrees.')

r_sq = rf.score(features, labels)
print("(R²):", r_sq)

print('MAE:', metrics.mean_absolute_error(test_labels, predictions_rf))
print('MSE:', metrics.mean_squared_error(test_labels, predictions_rf))
print('RMSE:', np.sqrt(metrics.mean_squared_error(test_labels, predictions_rf)))

Mean Absolute Error: 19122.89 degrees.
(R²): 0.9485886719577706
MAE: 19122.88696441281
MSE: 937331048.1581936
RMSE: 30615.862688452755

In [108]:
ada = AdaBoostRegressor(n_estimators=1000)
ada.fit(train_features, train_labels)
ada_pred = ada.predict(test_features)

errors_ada = abs(ada_pred - test_labels)

r_sq = ada.score(features,labels)
print("R2:",r_sq)
print('MAE:', metrics.mean_absolute_error(test_labels, ada_pred))
print('MSE:', metrics.mean_squared_error(test_labels, ada_pred))
print('RMSE:', np.sqrt(metrics.mean_squared_error(test_labels, ada_pred)))

R2: 0.8653412450242568
MAE: 25032.475258274764
MSE: 1434728710.275704
RMSE: 37877.81290248559

In [107]:
gbr = GradientBoostingRegressor(n_estimators=1000)
gbr.fit(train_features, train_labels)
gbr_pred = grb.predict(test_features)

errors_gbr = abs(gbr_pred - test_labels)
r_sq = gbr.score(features,labels)

print("R2:",r_sq)
print('MAE:', metrics.mean_absolute_error(test_labels, gbr_pred))
print('MSE:', metrics.mean_squared_error(test_labels, gbr_pred))
print('RMSE:', np.sqrt(metrics.mean_squared_error(test_labels, gbr_pred)))

R2: 0.971466617060163
MAE: 18332.84211863362
MSE: 801481352.897288
RMSE: 28310.446003150286